x=as.integer(readline(prompt="Enter your first number"))
y=as.integer(readline(prompt="Enter your second number"))
print("Product of the two numbers")
print(prod(x,y))
print("Average of the two numbers")
print(mean(x,y))
